import os
import json
import asyncio
import pandas as pd
import matplotlib.pyplot as plt
import datetime

from google.adk.agents import Agent, LlmAgent, ParallelAgent, SequentialAgent
from google.adk.tools import FunctionTool, AgentTool

# Import other components
from utility_agents.market_data.agent import root_agent as market_data_agent
from .filters import robust_gibbs_aggregation_tool
from .experts import moe_parallel_swarm
from .indicators import enrich_ohlcv_data

# ---------------------------------------------------------
# Phase 1: Data Ingestion Pipeline
# ---------------------------------------------------------
def data_ingestion_stub():
    """Tool that extracts market data using the specialized market_data package."""
    return "data/spy_2025_mock.csv" # [STUB] Usually this runs the live market_data_agent for Yahoo Finance

market_data_tool = FunctionTool(func=data_ingestion_stub)

market_extractor = LlmAgent(
    name="MarketDataExtractor",
    model="gemini-2.5-flash",
    instruction="Use the DataIngestionTool to extract 10 years of OHLCV historical data and news for the SPY ticker. Structure this data logically.",
    tools=[market_data_tool],
    output_key="structured_market_data"
)

technical_indicators_tool = FunctionTool(func=enrich_ohlcv_data)

quantitative_feature_agent = LlmAgent(
    name="QuantitativeFeatureAgent",
    model="gemini-2.5-flash",
    instruction="Take the output from {structured_market_data} (which is a CSV file path) and use the technical_indicators_tool to calculate MoE-F technical indicators (MACD, Bollinger, RSI, CCI, DX, SMAs).",
    tools=[technical_indicators_tool],
    output_key="enriched_market_data"
)

sbert_news_filter = LlmAgent(
    name="SBERT_SemanticFilter",
    model="gemini-2.5-flash",
    instruction="Apply similarity search to headlines in {enriched_market_data}. Discard noise below 0.2 tf-idf threshold and output the precise news chunks.",
    output_key="filtered_news_context"
)

market_data_pipeline = SequentialAgent(
    name="NIFTY_Ingestion_Pipeline",
    sub_agents=[market_extractor, quantitative_feature_agent, sbert_news_filter]
)

# ---------------------------------------------------------
# Phase 2: Swarm (ParallelFilterPhase) (imported above)
# ---------------------------------------------------------
# moe_parallel_swarm
# [STUB] NOTE: For live runs, the expert_llama, expert_gpt, and expert_mixtral LlmAgents (defined in experts.py)
# would be triggered here to produce predictions against the live API, invoking the stochastic_filter_update_tool.

# ---------------------------------------------------------
# Phase 3: Robust Aggregator (Coordinator Synthesizer)
# ---------------------------------------------------------
aggregator_agent = LlmAgent(
    name="SynthesizerAgent",
    model="gemini-2.5-flash",
    instruction="Execute the robust_gibbs_aggregation tool using the probability constraints previously generated by the Swarm.",
    tools=[robust_gibbs_aggregation_tool],
    output_key="synthesized_history_context"
)

# ---------------------------------------------------------
# Phase 4: Visualization & Plotting (Reporting Agent)
# ---------------------------------------------------------
def render_moe_trajectories(state) -> str:
    # 7-day rolling window simulation as defined in paper's methodology
    y_final = state.get("final_prediction", 0.5)
    history_file = os.path.join(os.path.dirname(__file__), "moe_history.csv")
    
    # Normally we load the history and append, here we'll simulate the rolling 
    try:
        # Load existing history if present
        if os.path.exists(history_file):
            df_hist = pd.read_csv(history_file)
        else:
            df_hist = pd.DataFrame(columns=["Turn", "y_true", "moef_prediction"])
        
        # We append a mock ground truth and new prediction 
        # (Assuming y_true is evaluated outside during final_test simulations)
        turn_index = len(df_hist)
        new_row = {"Turn": turn_index, "y_true": state.get("current_ground_truth", 0.5), "moef_prediction": y_final}
        df_hist = pd.concat([df_hist, pd.DataFrame([new_row])], ignore_index=True)
        df_hist.to_csv(history_file, index=False)
        
        # If sufficient history, apply rolling
        if len(df_hist) >= 7:
            # 7-day smoothing
            df_hist['rolling_moe'] = df_hist['moef_prediction'].rolling(window=7).mean()
            
            plt.figure(figsize=(12, 6))
            plt.plot(df_hist['Turn'], df_hist['y_true'], color='black', label='True Market Trajectory (Ground Truth)', linewidth=2)
            plt.plot(df_hist['Turn'], df_hist['rolling_moe'], color='green', linestyle='--', label='MoE-F Filtered Trajectory (7-Day)', linewidth=2)
            
            # Formatting as required by paper Figure 1
            plt.yticks([0.0, 0.5, 1.0], ['Bearish (0.0)', 'Neutral (0.5)', 'Bullish (1.0)'])
            plt.xlabel('Trading Days (2025)')
            plt.ylabel('Market Movement Direction / Regime')
            plt.title('MoE-F Mechanism 7-Day Rolling Trajectory vs Ground Truth (SPY 2025)')
            plt.legend()
            plt.grid(True)
            
            chart_path = os.path.join(os.path.dirname(__file__), "moe_regimes.png")
            plt.savefig(chart_path, bbox_inches='tight')
            plt.close()
            return f"Chart correctly rendered with 7-day rolling window at {chart_path}."
        else:
            return "Not enough data for 7-day rolling window. Accumulating predictions."
            
    except Exception as e:
        return f"Plotting failed: {str(e)}"

render_tool = FunctionTool(func=render_moe_trajectories)

plotting_agent = LlmAgent(
    name="PlottingAgent",
    model="gemini-2.5-flash",
    instruction="You are the visualization reporter. Trigger the RenderMoETrajectories tool using the history from {synthesized_history_context}.",
    tools=[render_tool],
    output_key="final_status"
)

# ---------------------------------------------------------
# Phase 5: Master Orchestration via Sequential Pipeline
# ---------------------------------------------------------
moef_level_3_system = SequentialAgent(
    name="MoEF_Pipeline",
    sub_agents=[market_data_pipeline, moe_parallel_swarm, aggregator_agent, plotting_agent]
)

# Compatibility stub mimicking the previous root agent for standard evaluations
root_agent = moef_level_3_system
